name: anro_lab

on:
  # Triggered whenever push to the main branch
  push:
    branches:
      - main
      - testing_ci_ros2

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: ["main", "testing_ci_ros2"]
    types: [opened]


jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup workspace
        run: |
          mkdir -p ros_ws/src/anro_lab
      - uses: actions/checkout@v3
        with:
          path: ros_ws/src/anro_lab
      - name: Configure linter
        run: |
          sudo apt update
          pip3 install ruff
          ruff check ros_ws/src/


  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04

    steps:
      
      # Install some system pacakges
      - name: Install ROS 2 Humble packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions ros-dev-tools
          sudo apt install -y lcov

      - name: Setup Workspace
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ros_ws/src/anro_lab
          cd ros_ws
          colcon build
          source install/setup.bash

      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
        with:
          path: ros_ws/src/anro_lab

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update --include-eol-distros
          cd ros_ws
          rosdep install --from-paths src -y --ignore-src
          colcon build --packages-select lab2_v2
          
